---
apiVersion: v1
kind: ConfigMap
metadata:
    name: sshd-authorized-keys
    namespace: sshd-tests
data:
    support_authorized_keys: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPcvk/x+RI3KKnwWOecibxBjLDxDwJM1vaZDQn+69Gbq0uj79TBq2ErW8LNzN3oUIAi2B9zEwKw6WRnFzlQLDmE09Vxpamh0R7kpUSIKy9AN/W/PQWeaambc01+WhtjNv+2DiMHnnloQNXAD4e+HCK/zsMr6FmLv7t43SPWK0f4OPPsRZReuEtzs57TNpo89svbrdpIvSxo6y59wYE/16IueE4CYl4e8gGGolbLsVPpT8UwpamtVrbeFGFOZTljqsccZAS3l9ow3jCZOKpGtUcby0rIIcP0vLrv0N6pOR2FM0DF3dPVn6gvSQcHgOQtFF8WNRRNd51AdxwVzQ9PN8L tobi@LCE31418
