---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-deployment
  namespace: sshd-tests
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: schulcloud/sshd:448c476c482830d6c68cef25eb119da81290f4c7
        ports:
        - containerPort: 22
        volumeMounts:
        - name: authorized-keys
          mountPath: "/home/support/.ssh/authorized_keys"
          subPath: support_authorized_keys
          # readOnly: true
        # - name: authorized-keys
        #   mountPath: "/home/support/.ssh"
          # readOnly: true
      volumes:
      - name: authorized-keys
        configMap:
          name: sshd-authorized-keys
          # items:
          #   - key: authorized_keys
          #     path: authorized_keys