---
apiVersion: v1
kind: Service
metadata:
  name: sshd-service
  namespace: sshd-tests
  labels:
    app: sshd
spec:
  # type: LoadBalancer
  selector:
    app: sshd
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
