---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+p[0-9]+'
  workflow_dispatch:
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.image_tag}}
    steps:
      - name: Ensure that the workflow runs only on tags
        run: |
          if [[ "$GITHUB_REF" != refs/tags/* ]]; then
            echo "This workflow only runs on tags"
            exit 1
          fi
      - name: Generate image tag with date
        id: generate_tag
        run: echo "image_tag=${GITHUB_REF_NAME}-$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

  build_and_push:
    needs:
      - pre_build
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@094a0e74897bef119a5a8fc73da781ff1f2274e6 # 8.4.2
    with:
      image_name: "infra-sshd"
      run_trivy_scan: true
      image_tag_generation: specified
      image_tag: ${{ needs.pre_build.outputs.image_tag }}
      add_latest_tag: true
      container_registry: "ghcr.io"
