---
name: Build and push Docker Image on Tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  generate_image_tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.image_tag}}
    steps:
      - name: Generate image tag with date
        id: tag
        run: |
          echo image_tag=${GITHUB_REF_NAME}-$(date +'%Y%m%d') >> $GITHUB_OUTPUT

  build_and_push:
    needs:
      - generate_image_tag
    uses: hpi-schul-cloud/infra-tools/.github/workflows/build-and-push.yaml@master
    with:
      image: schulcloud/infra-sshd
      tag: ${{ needs.generate_image_tag.outputs.image_tag }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
