---
name: Build and push Docker Image on Tag

on:
  push:
    # tags:
    #   - '[0-9]+.[0-9]+.[0-9]+'
    paths:
      - '.github'
  workflow_dispatch:
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate_tag.outputs.image_tag}}
    steps:
      - name: Ensure that the workflow runs only on tags
        run: |
          if [[ "$GITHUB_REF" != refs/tags/* ]]; then
            echo "This workflow only runs on tags"
            exit 1
          fi
      - name: Generate image tag with date
        id: generate_tag
        run: echo "image_tag=${GITHUB_REF_NAME}-$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

  build_and_push:
    needs:
      - pre_build
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.pre_build.outputs.image_tag }}"
    # uses: hpi-schul-cloud/infra-tools/.github/workflows/build-and-push.yaml@master
    # with:
    #   image: schulcloud/infra-sshd
    #   tag: ${{ needs.generate_image_tag.outputs.image_tag }}
    # secrets:
    #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #   DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
