---
name: Docker Image Trivy Image Vulnerability Scan Cron Job
on:
  schedule:
    # Runs "at 2 a.m. past every day" (see https://crontab.guru)
    - cron: '0 2 * * *'
  workflow_dispatch:
permissions:
  # required for all workflows
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  trivy_image_scan_cron:
    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/check-trivy.yaml@9bfc5de7a4cde05925607a4d34944b197b37064c
    with:
      image_ref: "ghcr.io/dbildungsplattform/infra-sshd:latest"
  