---
name: Docker Image Trivy Image Vulnerability Scan Cron Job
on:
  schedule:
    # Runs "at 2 a.m. past every day" (see https://crontab.guru)
    - cron: '0 2 * * *'
  workflow_dispatch:
permissions:
  # required for all workflows
  security-events: write
  packages: read
  contents: read

jobs:
  trivy_image_scan_cron:
    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/check-trivy.yaml@4b5c0434f28b537e9199ffebc21f4e6e39cbcdde # 8.4.3
    with:
      image_ref: "ghcr.io/dbildungsplattform/infra-sshd:latest"
  