---
name: Docker Image Trivy Image Vulnerability Scan Cron Job
on:
  schedule:
    # Runs "at 2 a.m. past every day" (see https://crontab.guru)
    - cron: '0 2 * * *'
  workflow_dispatch:
permissions:
  # required for all workflows
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

# Template Single Image Repro GHA
jobs:
  trivy_image_scan_cron:
    uses: dbildungsplattform/infra-tools/.github/workflows/trivy-scan.yaml@094a0e74897bef119a5a8fc73da781ff1f2274e6 # 8.4.2
    with:
      image-ref: 'ghcr.io/dbildungsplattform/infra-sshd:latest'
